### ISSUE TITLE
View: Landing Page

### ISSUE THREAD

**Issue by Jovany1543** [Jovany1543/Project-Ares#1]
Story: "As a visitor, I want to be able to quickly identify where to go for what I want to see or know."

Features
- [ ] one row of cards for each type of firearms #13 
- [ ] a row of cards for uses of firearms #14 
- [ ] linking to information regarding gun safety and other general knowledge regarding firearms #20
