### ISSUE TITLE
View: Bookmarks Page

### ISSUE THREAD

**Issue by Jovany1543** [Jovany1543/Project-Ares#4]
As a user, I would like a page for all the weapons I have bookmarked. I would like the ability to search through my bookmarks and sort by ascending or descending order.

Features
- [ ] List of bookmarks #24 
- [ ] Search #25 
- [ ] Button that toggles ascending or descending order #26 
- [ ] Option to delete #27
